version: "3"

services:
  matchoutcome:
    image: ciarangrant/matchoutcome:v20240305
    volumes:
      - /opt/AFL_Data:/AFL_Data
    deploy:
      labels:
        - traefik.enable=true
        - traefik.http.services.matchoutcome.loadbalancer.server.port=8000
        
        - traefik.http.routers.matchoutcome.entrypoints=websecure
        - traefik.http.routers.matchoutcome.rule=Host(`ciarandgrant.com`)
        - traefik.http.routers.matchoutcome.tls=true
        - traefik.http.routers.matchoutcome.service=matchoutcome
        - traefik.http.routers.matchoutcome.middlewares=authelia@docker
      restart_policy:
        condition: on-failure
    networks:
      - Traefik_overlay

networks:
  Traefik_overlay:
    external: true